# fly.toml app configuration file generated for weddingfest on 2023-06-23T15:19:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weddingfest"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "npm run release"

[env]
  PORT = "8080"
  PRIMARY_REGION = "ams"

[mounts]
  source = "weddingfest_data"
  destination = "/weddingfest/images"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/healthcheck"
    protocol = "http"

[[services]]
  protocol = ["tls", "ssh"]
  internal_port = 22

  [[services.ports]]
    port = "3022"
